version: 2
jobs:
  build:
    docker:
     - image: cimg/go:1.13

    working_directory: ~/
    environment:
      OPERATOR_KEY: "b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291"
      CHALLENGER_KEY: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a114"
      OPERATOR: "0x71562b71999873DB5b286dF957af199Ec94617F7"
      CHALLENGER: "0x3616BE06D68dD22886505e9c2CaAa9EcA84564b8"
      ADDR0: "0x5df7107c960320b90a3d7ed9a83203d1f98a811d"
      ADDR1: "0x3cd9f729c8d882b851f8c70fb36d22b391a288cd"
      ADDR2: "0x57ab89f4eabdffce316809d790d5c93a49908510"
      ADDR3: "0x6c278df36922fea54cf6f65f725267e271f60dd9"
      KEY0: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a115"
      KEY1: "bfaa65473b85b3c33b2f5ddb511f0f4ef8459213ada2920765aaac25b4fe38c5"
      KEY2: "067394195895a82e685b000e592f771f7899d77e87cc8c79110e53a2f0b0b8fc"
      KEY3: "ae03e057a5b117295db86079ba4c8505df6074cdc54eec62f2050e677e5d4e66"
      DATADIR_ROOTCHAIN: "/home/circleci/go-ethereum/chaindata"
      DATADIR_MANAGERS: "/home/circleci/plasma-evm/pls.manager"
      DATADIR_OPERATOR1: "/home/circleci/plasma-evm/pls.oper1"
      DATADIR_OPERATOR2: "/home/circleci/plasma-evm/pls.oper2"
    steps:
      - run:
          name: Compile rootchain
          command: |
            set -x
            git clone https://github.com/Onther-Tech/go-ethereum
            cd go-ethereum
            make geth

      - run:
          name: Compile childchain as operator
          command: |
            set -x
            git clone https://github.com/Onther-Tech/plasma-evm
            cd plasma-evm
            make geth
            echo "" > signer.pass
            build/bin/geth --nousb account importKey $KEY0 --password signer.pass --datadir $DATADIR_MANAGERS
            build/bin/geth --nousb account importKey $KEY1 --password signer.pass --datadir $DATADIR_OPERATOR1
            build/bin/geth --nousb account importKey $KEY2 --password signer.pass --datadir $DATADIR_OPERATOR2
            echo "for i in {1..5}" >> sendTx.operator1.sh
            echo "do" >> sendTx.operator1.sh
            echo "  ../build/bin/geth --exec 'web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})' attach --datadir ./" >> sendTx.operator1.sh
            echo "  sleep 30" >> sendTx.operator1.sh
            echo "done" >> sendTx.operator1.sh
            echo "" > pwd.pass

      - run:
          name: Run rootchain
          background: true
          command: |
            set -x
            cd go-ethereum
            build/bin/geth \
            --dev \
            --dev.period 1 \
            --dev.faucetkey "$OPERATOR_KEY,$CHALLENGER_KEY,$KEY0,$KEY1,$KEY2,$KEY3" \
            --datadir $DATADIR_ROOTCHAIN \
            --rpc \
            --rpcport 8545 \
            --rpcapi eth,debug,net \
            --rpcaddr 0.0.0.0 \
            --ws \
            --wsport 8546 \
            --wsaddr 0.0.0.0 \
            --wsapi eth,debug,net \
            --miner.gastarget 7500000 \
            --miner.gasprice "10"

      - run:
          name: Setup childchain as operator
          command: |
            set -x
            cd plasma-evm
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8545
            build/bin/geth \
              --nousb \
              --rootchain.url "ws://127.0.0.1:8546" \
              --operator.key $KEY0 \
              --rootchain.sender $ADDR0 \
              --datadir $DATADIR_OPERATOR1 \
              deploy "./genesis.json" 16 true 2
            build/bin/geth --nousb init --rootchain.url "ws://127.0.0.1:8546" --datadir $DATADIR_OPERATOR1 genesis.json

      - run:
          name: Run childchain, Operator1
          background: true
          command: |
            set -x
            cd plasma-evm
            build/bin/geth \
              --rootchain.url "ws://127.0.0.1:8546" \
              --datadir $DATADIR_OPERATOR1 \
              --operator $ADDR0 \
              --password pwd.pass \
              --unlock $ADDR0 \
              --rpc \
              --rpcport 8547 \
              --port 30306 \
              --allow-insecure-unlock

      - run:
          name: Send Tx & Check blocknumber in childchain
          command: |
            cd plasma-evm
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8547
            build/bin/geth --exec "web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})" attach --datadir $DATADIR_OPERATOR1
            sleep 10
            build/bin/geth --exec "web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})" attach --datadir $DATADIR_OPERATOR1
            sleep 10
            build/bin/geth --exec "web3.eth.blockNumber" attach --datadir $DATADIR_OPERATOR1

      - save_cache:
          key: plasma-evm-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/

  test:
    docker:
      - image: cimg/go:1.13

    working_directory: ~/
    environment:
      OPERATOR_KEY: "b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291"
      CHALLENGER_KEY: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a114"
      OPERATOR: "0x71562b71999873DB5b286dF957af199Ec94617F7"
      CHALLENGER: "0x3616BE06D68dD22886505e9c2CaAa9EcA84564b8"
      ADDR0: "0x5df7107c960320b90a3d7ed9a83203d1f98a811d"
      ADDR1: "0x3cd9f729c8d882b851f8c70fb36d22b391a288cd"
      ADDR2: "0x57ab89f4eabdffce316809d790d5c93a49908510"
      ADDR3: "0x6c278df36922fea54cf6f65f725267e271f60dd9"
      KEY0: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a115"
      KEY1: "bfaa65473b85b3c33b2f5ddb511f0f4ef8459213ada2920765aaac25b4fe38c5"
      KEY2: "067394195895a82e685b000e592f771f7899d77e87cc8c79110e53a2f0b0b8fc"
      KEY3: "ae03e057a5b117295db86079ba4c8505df6074cdc54eec62f2050e677e5d4e66"
      DATADIR_ROOTCHAIN: "/home/circleci/go-ethereum/chaindata"
      DATADIR_MANAGERS: "/home/circleci/plasma-evm/pls.manager"
      DATADIR_OPERATOR1: "/home/circleci/plasma-evm/pls.oper1"
      DATADIR_OPERATOR2: "/home/circleci/plasma-evm/pls.oper2"

    steps:
      - restore_cache:
          key: plasma-evm-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/

      - run:
          name: Run rootchain
          background: true
          command: |
            set -x
            rm -rf $DATADIR_ROOTCHAIN/keystore
            go-ethereum/build/bin/geth \
            --dev \
            --dev.period 1 \
            --dev.faucetkey "$OPERATOR_KEY,$CHALLENGER_KEY,$KEY0,$KEY1,$KEY2,$KEY3" \
            --datadir $DATADIR_ROOTCHAIN \
            --rpc \
            --rpcport 8545 \
            --rpcapi eth,debug,net \
            --rpcaddr 0.0.0.0 \
            --ws \
            --wsport 8546 \
            --wsaddr 0.0.0.0 \
            --wsapi eth,debug,net \
            --miner.gastarget 7500000 \
            --miner.gasprice "10"

      - run:
          name: Test manage-staking command(1/7) - deployManagers
          command: |
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8546
            cd plasma-evm
            build/bin/geth manage-staking deployManagers 10 1.5 \
              --datadir $DATADIR_MANAGERS \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test manage-staking command(2/7) - mintTON
          command: |
            cd plasma-evm
            build/bin/geth manage-staking mintTON $ADDR1 10000.0 \
              --datadir $DATADIR_MANAGERS \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test manage-staking command(3/7) - deployPowerTON
          command: |
            cd plasma-evm
            build/bin/geth manage-staking deployPowerTON 30s \
              --datadir $DATADIR_MANAGERS \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test manage-staking command(4/7) - startPowerTON
          command: |
            cd plasma-evm
            build/bin/geth manage-staking startPowerTON \
              --datadir $DATADIR_MANAGERS \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test manage-staking command(4/7) - getManagers
          command: |
            cd plasma-evm
            build/bin/geth manage-staking getManagers managers.json \
              --datadir $DATADIR_MANAGERS

      - run:
          name: Test manage-staking command(6/7) - setManagers
          command: |
            cd plasma-evm
            build/bin/geth manage-staking setManagers managers.json \
              --datadir $DATADIR_OPERATOR1

      - run:
          name: Test manage-staking command(7/7) - register
          command: |
            cd plasma-evm
            build/bin/geth manage-staking register \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test staking command(1/5) - swapFromTON
          command: |
            cd plasma-evm
            build/bin/geth staking swapFromTON 1000.0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test staking command(2/5) - swapToTON
          command: |
            cd plasma-evm
            build/bin/geth staking swapToTON 500.0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test staking command(3/5) - stakeWTON
          command: |
            cd plasma-evm
            build/bin/geth staking stakeWTON 250.0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test staking command(4/5) - stakeTON
          command: |
            cd plasma-evm
            build/bin/geth staking stakeTON 250.0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Test staking command(5/5) - balances
          command: |
            cd plasma-evm
            build/bin/geth staking balances $ADDR0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

      - run:
          name: Run childchain, Operator1
          background: true
          command: |
            set -x
            cd plasma-evm
            build/bin/geth \
              --rootchain.url "ws://127.0.0.1:8546" \
              --datadir $DATADIR_OPERATOR1 \
              --operator $ADDR0 \
              --password pwd.pass \
              --unlock $ADDR0 \
              --rpc \
              --rpcport 8547 \
              --port 30306 \
              --allow-insecure-unlock

      - run:
          name: Proceed operator1 blocks by send dummy tx
          command: |
            cd plasma-evm
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8547
            bash sendTx.operator1.sh

      - run:
          name: Check balance of Operator1 after block proceed
          command: |
            cd plasma-evm
            build/bin/geth staking balances $ADDR0 \
              --datadir $DATADIR_OPERATOR1 \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build