version: 2
jobs:
  build:
    docker:
     - image: cimg/go:1.13

    working_directory: ~/
    environment:
      OPERATOR_KEY: "b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291"
      OPERATOR: "0x71562b71999873DB5b286dF957af199Ec94617F7"

    steps:
      - run:
          name: Compile rootchain
          command: |
            set -x
            git clone https://github.com/Onther-Tech/go-ethereum
            cd go-ethereum
            make geth

      - run:
          name: Compile childchain as operator
          command: |
            set -x
            git clone https://github.com/Onther-Tech/plasma-evm
            cd plasma-evm
            make geth
            echo "" > signer.pass
            build/bin/geth --nousb account importKey b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291 --password signer.pass --datadir ./pls.oper
            echo "while :" >> sendTx.operator1.sh
            echo "do" >> sendTx.operator1.sh
            echo "  ../build/bin/geth --exec 'web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})' attach --datadir ./" >> sendTx.operator1.sh
            echo "  sleep 30" >> sendTx.operator1.sh
            echo "done" >> sendTx.operator1.sh
            echo "" > pwd.pass

      - run:
          name: Run rootchain
          background: true
          command: |
            set -x
            cd go-ethereum
            build/bin/geth \
            --dev \
            --dev.period 1 \
            --dev.faucetkey "$OPERATOR_KEY" \
            --rpc \
            --rpcport 8545 \
            --rpcapi eth,debug,net \
            --rpcaddr 0.0.0.0 \
            --ws \
            --wsport 8546 \
            --wsaddr 0.0.0.0 \
            --wsapi eth,debug,net \
            --miner.gastarget 7500000 \
            --miner.gasprice "10"

      - run:
          name: Setup childchain as operator
          command: |
            set -x
            cd plasma-evm
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8545
            build/bin/geth --nousb --rootchain.url "ws://127.0.0.1:8546" --operator.key $OPERATOR_KEY --rootchain.sender $OPERATOR --datadir pls.oper deploy "./genesis.json" 16 true 4096
            build/bin/geth --nousb init --rootchain.url "ws://127.0.0.1:8546" --datadir pls.oper genesis.json

      - run:
          name: Run childchain
          background: true
          command: |
            set -x
            cd plasma-evm
            build/bin/geth --rootchain.url "ws://127.0.0.1:8546" --datadir ./pls.oper --rpc --rpcport 8547 --operator $OPERATOR --port 30306

      - run:
          name: Send Tx & Check blocknumber in childchain
          command: |
            cd plasma-evm
            curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":67}' -H 'Content-Type: application/json' --retry 100 --retry-delay 3 --retry-connrefused  http://127.0.0.1:8547
            build/bin/geth --exec "web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})" attach --datadir ./pls.oper
            sleep 10
            build/bin/geth --exec "web3.eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[0], value: 0})" attach --datadir ./pls.oper
            sleep 10
            build/bin/geth --exec "web3.eth.blockNumber" attach --datadir ./pls.oper

      - save_cache:
          key: plasma-evm-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
            - /tmp

  test:
    docker:
      - image: cimg/go:1.13

    working_directory: ~/
    environment:
      OPERATOR_KEY: "b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291"
      CHALLENGER_KEY: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a114"
      OPERATOR: "0x71562b71999873DB5b286dF957af199Ec94617F7"
      CHALLENGER: "0x3616BE06D68dD22886505e9c2CaAa9EcA84564b8"
      ADDR0: "0x5df7107c960320b90a3d7ed9a83203d1f98a811d"
      ADDR1: "0x3cd9f729c8d882b851f8c70fb36d22b391a288cd"
      ADDR2: "0x57ab89f4eabdffce316809d790d5c93a49908510"
      ADDR3: "0x6c278df36922fea54cf6f65f725267e271f60dd9"
      KEY0: "78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a115"
      KEY1: "bfaa65473b85b3c33b2f5ddb511f0f4ef8459213ada2920765aaac25b4fe38c5"
      KEY2: "067394195895a82e685b000e592f771f7899d77e87cc8c79110e53a2f0b0b8fc"
      KEY3: "ae03e057a5b117295db86079ba4c8505df6074cdc54eec62f2050e677e5d4e66"

    steps:
      - restore_cache:
          key: plasma-evm-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/
            - /tmp

      - run:
          name: Run rootchain
          background: true
          command: |
            set -x
            go-ethereum/build/bin/geth \
            --dev \
            --dev.period 1 \
            --dev.faucetkey "$OPERATOR_KEY" \
            --rpc \
            --rpcport 8545 \
            --rpcapi eth,debug,net \
            --rpcaddr 0.0.0.0 \
            --ws \
            --wsport 8546 \
            --wsaddr 0.0.0.0 \
            --wsapi eth,debug,net \
            --miner.gastarget 7500000 \
            --miner.gasprice "10"

      - run:
          name: Run childchain
          background: true
          command: |
            set -x
            cd plasma-evm/pls.oper
            ../build/bin/geth --rootchain.url "ws://127.0.0.1:8546" --datadir ./ --operator $OPERATOR --port 30306

      - run:
          name: Test staking command - deployManagers
          command: |
            build/bin/geth manage-staking deployManagers 10 1.5 \
              --datadir $DATADIR_MANAGERS \
              --rootchain.url "ws://127.0.0.1:8546" \
              --unlock $ADDR0 \
              --password pwd.pass \
              --rootchain.sender $ADDR0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build