version: 2
jobs:
  build:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01

    working_directory: /home/circleci
    environment:
      OPERATOR_KEY="b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291"
      CHALLENGER_KEY="78ae75d1cd5960d87e76a69760cb451a58928eee7890780c352186d23094a114"
      OPERATOR="0x71562b71999873DB5b286dF957af199Ec94617F7"
      CHALLENGER="0x3616BE06D68dD22886505e9c2CaAa9EcA84564b8"
      GOROOT=/home/circleci/go
      GOPATH=/home/circleci/plasma
      PATH=$GOPATH/bin:$GOROOT/bin:$PATH

    steps:
      - run:
          name: Setup environment
          command: |
            set -x
            env
            wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
            tar -xvf go1.13.4.linux-amd64.tar.gz
            which go

      - run:
          name: Run rootchain
          command: |
            set -x
            git clone https://github.com/Onther-Tech/go-ethereum
            cd go-ethereum
            nohup bash run.rootchain.sh &
            tail -n 100 nohup.out

      - run:
          name: Run Operator Node
          command: |
            set -x
            git clone -b circleci https://github.com/sifnoc/plasma-evm
            cd plasma-evm
            make geth && build/bin/geth --nousb --rootchain.url "ws://localhost:8546" --operator.key $OPERATOR_KEY --rootchain.sender $OPERATOR --datadir pls.oper deploy "./genesis.json" 16 true 4096
            build/bin/geth --nousb init --rootchain.url "ws://localhost:8546" --datadir pls.oper genesis.json
            echo "" > signer.pass
            build/bin/geth --nousb account importKey b71c71a67e1177ad4e901695e1b4b9ee17ae16c6668d313eac2f96dbcda3f291 --nousb --password signer.pass --datadir ./pls.oper
